### ISSUE TITLE
IEEE 802.15.4 Implementation.

### ISSUE THREAD

**Issue by dak-x** [blueluna/psila#2]
I wish to implement the 6LoWPAN standard on no_std rust. Right now I'm searching for IEEE 802.15.4 link-layer implementations. It would be really helpful If you can point me towards the relevant sections. Right now Im looking at the psila-data crate. Thank You!

**Comment by blueluna** [comment]
Have a look at,
https://github.com/braun-embedded/rust-ieee802.15.4

Best regards.
