### ISSUE TITLE
std lib

### ISSUE THREAD

**Issue by lattice0** [blueluna/psila#4]
Are there plans to not use the std lib? I know nothing about embedded devices, but it looks like would be nicer to have no std in this one. I'm trying to put it into the ESP32 and had to activate std stuff.

I don't know, it looks like this MCU is too slow for std

**Comment by blueluna** [comment]
Psila is usable in an no_std environment, I have used it in nrf52840 which has less resources than esp32. Just use the "core" feature. For a full example, see:
https://github.com/blueluna/nrf52840-experiments/tree/master/adafruit-feather-nrf52840-express

I am trying to see if a ESP32-C6 example is possible with Psila.

**Comment by blueluna** [comment]
Does this answer your question? Can we close this issue?
